#!/bin/sh
#
# Fastest way to change monitor brightness

usage() {
	echo "Usage: brightness [0...5]"
}

if [ "$#" -eq 1 ]; then
	xrandr --output DP-0 --brightness $1
	xrandr --output HDMI-0 --brightness $1
else
	usage
fi
