#!/bin/sh
#
# Prints current connected bluetooth device name and battery on stdout, statusbar etc

CONNECTED=$(bluetoothctl info | grep "Connected: yes")
if [ -z "$CONNECTED" ]; then
	echo ""
	exit 0
fi

INFO=$(bluetoothctl info)

DEVICE_NAME=$(echo "$INFO" | sed -n 's/.*Name: \(.*\)/\1/p')

BATTERY=$(echo "$INFO" | sed -n 's/.*Battery Percentage: 0x[0-9A-Fa-f]* (\([0-9]*\)).*/\1/p')

if [ -n "$DEVICE_NAME" ] && [ -n "$BATTERY" ]; then
  echo "󰂯 ${DEVICE_NAME} ${BATTERY}%"
fi

