#!/bin/sh
#
# Prints current connected bluetooth device name and battery on stdout, statusbar etc

connected=$(bluetoothctl info | grep "Connected: yes")
if [ -z "$connected" ]; then
	echo ""
	exit 0
fi

info=$(bluetoothctl info)

device_name=$(echo "$INFO" | sed -n 's/.*Name: \(.*\)/\1/p')

battery=$(echo "$INFO" | sed -n 's/.*Battery Percentage: 0x[0-9A-Fa-f]* (\([0-9]*\)).*/\1/p')

if [ -n "$device_name" ] && [ -n "$battery" ]; then
  echo "󰂯 ${device_name} ${battery}%"
fi

