#!/bin/sh
#
# Fast backup

. $HOME/scripts/config

DATE="$(date +%Y)-$(date +%m)-$(date +%d)-$(date +%H)-$(date +%M)"
BACKUP_DIR=$HOME"/backup"$DATE

mkdir -p $BACKUP_DIR
mkdir -p $BACKUP_DIR/suckless

cp -r $HOME/suckless $BACKUP_DIR/suckless

for f in ${FILES[@]}; do
	cp -v $HOME/$f $BACKUP_DIR
done

for d in ${DIRS[@]}; do
	cp -v -r $HOME/$d $BACKUP_DIR
done

