#!/bin/sh
#
# Fast backup

set -xe

. $HOME/scripts/config

DATE="$(date +%Y)-$(date +%m)-$(date +%d)-$(date +%H)-$(date +%M)"
BACKUP_DIR=$HOME"/backup"$DATE

mkdir $BACKUP_DIR
mkdir -p $BACKUP_DIR/".config/nvim"
mkdir -p $BACKUP_DIR/".local/share/nvim"

cp -r "/home/guilherme/.config/nvim" $BACKUP_DIR/".config/nvim"
cp -r "/home/guilherme/.local/share/nvim" $BACKUP_DIR/".local/share/nvim"

for f in ${FILES[@]}; do
	cp -v $HOME/$f $BACKUP_DIR
done

for d in ${DIRS[@]}; do
	cp -v -r $HOME/$d $BACKUP_DIR
done


