#!/bin/sh
#
# Fast backup

DATE="$(date +%Y)-$(date +%m)-$(date +%d)-$(date +%H)-$(date +%M)"

mkdir -p $BACKUP_DIR
mkdir -p $BACKUP_DIR/suckless

cp -r $HOME/suckless $BACKUP_DIR/suckless

for f in ${FILES[@]}; do
	cp -v $HOME/$f $BACKUP_DIR
done

for d in ${DIRS[@]}; do
	cp -v -r $HOME/$f $BACKUP_DIR
done

