#!/bin/sh
#
# Get the status of a list of local git repositories

. $HOME/scripts/config

curr_path=`pwd`

for d in ${DIRECTORIES[@]}; do
	echo $(tput setaf 80) $d $(tput sgr0)
	cd $d  
	status=`git status | grep nothing`
	if [ "$status" = "" ];then
		echo -n $(tput setaf 124) 
		git status | grep -E 'modified|deleted|Untracked'
		echo -n $(tput sgr0)
	else 
		echo $status
	fi
done

cd $curr_path
