#!/bin/sh
#
# Search instructions in a file that contains instructions. 

. $HOME/scripts/config

if [ $# -ne 1 ]; then
    echo "Usage: $0 \"pattern\""
    exit 1
fi
pattern=$1
if [ ! -f "$HOWTO_FILE" ]; then
    echo "File $HOWTO_FILE not found!"
    exit 1
fi
found_pattern=false
minus_count=0
print_lines=false
while IFS= read -r line || [[ -n "$line" ]]; do
    if [[ "$line" == \#*"$pattern"* ]]; then
        found_pattern=true
        print_lines=true
		echo "$line"
        continue
    fi
    if [[ "$print_lines" == true ]]; then
        echo "$line"
        if [[ "$line" == "$(printf '%.0s-' {1..107})" ]]; then
            minus_count=$((minus_count + 1))
            if [[ $minus_count -ge 2 ]]; then
                break
            fi
        fi
    fi

done < "$HOWTO_FILE"
