#!/bin/sh
#
# Move the last screenshot taken to $1 directory

SCREENSHOTS_DIR=$HOME/pictures/screenshots

usage() {
	echo ""
	echo "Move the last screenshot taken to [destination]."
	echo ""
	echo "Usage: mvpic [destination]"
	echo ""
}

if [ $# -ne 1 ];then
	usage
	exit 1
else
	if [ -d "$1" ];then
		screenshot=$(ls -t $SCREENSHOTS_DIR | head -n 1)
		mv $SCREENSHOTS_DIR/$screenshot $1
	else
		echo "$1 is not a directory."
		exit 1
	fi
fi
