#!/bin/sh
#
# Opens my notes file (useful for dmenu)

. $HOME/scripts/config

if pstree -s $$ | grep -q xinit; then
	nvim -u $INIT_VIM_DIR $NOTES_DIR
else
	st -g 120x30-450-250-e nvim -u $INIT_VIM_DIR $NOTES_DIR
fi
