#!/usr/bin/python
#
# Open a file of links in firefox

import webbrowser
import sys


def openLinksInFirefox(file_path):
    try:
        with open(file_path, 'r') as file:
            links = file.readlines()
            for link in links:
                webbrowser.get('firefox').open(link.strip())
    except FileNotFoundError:
        print(f"File '{file_path}' not found.")


def usage():
    print("\nUSAGE:\n")
    print("openlinks /path/to/file\n")


if __name__ == '__main__':
    if len(sys.argv) != 2:
        usage()
        exit()
    openLinksInFirefox(sys.argv[1])

