#!/bin/sh
#
# Screenshot to a file and to clipboard simultaneously (useful for dwm keybinds)

SCREENSHOT_FILE_NAME=$HOME"/pictures/screenshots/%Y-%m-%d-%T-screenshot.png"

scrot $SCREENSHOT_FILE_NAME --select -e 'xclip -selection clipboard -target image/png -i $f'
