#!/bin/sh
#
# I don't know if there is a better way to do this (there is)
#
# https://docs.github.com/en/actions/security-for-github-actions/security-guides/automatic-token-authentication

. $HOME/scripts/config

if ! command -v xdotool >/dev/null 2>&1; then
    echo "xdotool is not installed."
    exit 1
fi

line_1=$(sed -n '1p' $TOKEN_DIR) 
line_2=$(sed -n '2p' $TOKEN_DIR)

if echo "$line_1" | grep -q '^#'; then 
    token=$line_2
else
    token=$line_1 
fi

press_keys() {
    len=${#token}
    i=0
    while [ $i -lt $len ]; do
        char=$(echo "$token" | cut -c $((i + 1)))
        if [ "$char" = "_" ]; then
            xdotool key underscore
        else
            xdotool type "$char"
        fi
        i=$((i + 1))
    done
    xdotool key Return
}

sleep 0.2
press_keys

