#!/bin/sh
#
# Practical way to change wallpaper

. $HOME/scripts/config

usage() {
	echo " "
	echo "Unknown option"
	echo " "
	echo "  -l               list wallpapers"
	echo "  -s [FILE]        set [FILE] as wallpaper"
	echo "  -f               open wallpapers in feh"
}

if [ "$1" = "-l" ]; then
	ls $WPP_DIR
elif [ "$1" = "-s" ]; then
	# TODO see if $1 contains .png | .jpg
	PIC_PATH=$WPP_DIR/$2
	if [ -f $PIC_PATH.jpg ]; then			
		feh --bg-scale $PIC_PATH.jpg
	elif [ -f $PIC_PATH.png ]; then
		feh --bg-scale $PIC_PATH.png
	else
		usage
		exit 1
	fi
elif [ "$1" = "-f" ]; then
	feh --scale-down -g 1914x1045 $WPP_DIR
else
	usage
fi
