#!/usr/bin/bash
#
# Practical way to change wallpaper

. ./config

if [ "$1" = "-l" ]; then
	ls $WPP_DIR
elif [ "$1" = "-s" ]; then
	PIC_PATH=$WPP_DIR/$2
	if [ -f $PIC_PATH.jpg ]; then			
		feh --bg-scale $PIC_PATH.jpg
	fi
	if [ -f $PIC_PATH.png ]; then
		feh --bg-scale $PIC_PATH.png
	else
		echo " "
		echo "Unknown option"
		echo " "
		echo "  -l               list wallpapers"
		echo "  -s [FILE]        set [FILE] as wallpaper"
		echo "  -lf              open wallpapers in lf"
		exit 1
	fi
elif [ "$1" = "-lf" ]; then
	lf $WPP_DIR
else
	echo "Unknown option"
	echo " "
	echo "  -l               list wallpapers"
	echo "  -s [FILE]        set [FILE] as wallpaper"
	echo "  -lf              open wallpapers in lf"
fi
